name: cicd pipeline

on:
  push:
    branches: [ main ]

jobs:
  build_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Clone the code
        uses: actions/checkout@v7
      - name: Trivy scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'fs'
          severity: HIGH,CRITICAL
          exit-code: '1'
      - name: Build Docker image
        run: docker build -t 267673636159.dkr.ecr.us-east-1.amazonaws.com/my-repo:latest .
      - name: Scan Docker image
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: 267673636159.dkr.ecr.us-east-1.amazonaws.com/my-repo:latest
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          severity: HIGH,CRITICAL
      - name: Push Docker image to ECR
        run: echo "Pushing Docker image to ECR..."