name: cicd pipeline

on:
  push:
    branches: [ main ]

permissions:
    id-token: write
    contents: read

jobs:
  build_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Clone the code
        uses: actions/checkout@v7
      - name: Trivy scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'fs'
          severity: HIGH,CRITICAL
          exit-code: '1'
      - name: Build Docker image
        run: docker build -t 267673636159.dkr.ecr.us-east-1.amazonaws.com/my-repo:latest .
      - name: Scan Docker image
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: 267673636159.dkr.ecr.us-east-1.amazonaws.com/my-repo:latest
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          severity: HIGH,CRITICAL
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::267673636159:role/github-action
          aws-region: us-east-1
      - name: Login to Amazon ECR 
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        